# -*- coding: utf-8 -*-
"""B4：database.cl3 行记录里定长内嵌名称字段的译文。

口径来源（优先级从高到低）：
  1. 已译好的 8396 条说明文里既成的专名译法（b4_gloss.py 自动挖出 358 条）
  2. 已经做进贴图的迷宫名横幅（tex/build_mapname.py）—— art 已交付，以它为准
  3. 剧情译文里出现过的地名
  4. 系统文本 / 菜单的正式口径（歌力 耐力 知识 神力 技巧 活力 等）
字段是定长的（32 或 64 字节），回填器会校验 UTF-8 字节数 + 1 个 NUL 不超过宽度。
"""

# ── 角色名（和 tr_speakers 一致）──────────────────────────────
CHARA = {
 'Takt': '塔克特', 'Otoha': '音羽', 'Kyouka': '响歌',
 'Kanadeko': '奏子', 'Nene': '祢祢', 'Aria': '艾莉亚', 'Momoka': '桃香',
}

# ── 迷宫名（以已交付的横幅贴图为准）──────────────────────────
DUNGEON = {
 'Verdant Greenbelt': '翠绿地带',
 'Arid Wilderness': '干涸荒野',
 'Skyscraper Shelter': '摩天避难所',
 'South Middleton': '南米德尔顿',
 'Middleton North': '北米德尔顿',
 'Crystal Cave': '水晶洞窟',
 'Yamate Town Ruins': '山手町遗迹',
 'Bayside Plant': '湾岸工厂',
 'Valley Supply Base': '溪谷补给基地',
 'Central Tower': '中央塔',
 'Theater Hall': '剧场大厅',
 'Nibashi Business District': '二桥商业区',
 'Daiba Canal Bridge': '台场运河桥',
 **{f'Training Facility [Floor {i}] ': f'训练设施 [{i}层]' for i in range(1, 14)},
}

# ── 地图地名（迷宫内分区 / 城镇分区）────────────────────────
MAPPOINT = {
 'Office': '事务所',
 'Town Map': '城镇地图',
 'World Map': '世界地图',
 'Verdant Greenbelt': '翠绿地带',
 'Wandering Triple-Fork': '彷徨三叉路',
 'Leafy Pond South': '绿叶池南',
 'Weathervane Plains': '风向标平原',
 'Winding Trail': '蜿蜒小径',
 'Stargazers Field': '观星者之地',
 'Misty Plateau': '迷雾高原',
 'Crystal Cave': '水晶洞窟',
 'Arid Wilderness': '干涸荒野',
 'Northern Wasteland': '北部荒地',
 'Western Wasteland': '西部荒地',
 'Underworld Trail': '冥界小径',
 'Valley Supply Base': '溪谷补给基地',
 'Skyscraper Shelter': '摩天避难所',
 'B1F Central': '地下1层中央',
 'Elevator': '电梯',
 'Corridor': '通道',
 'South Middleton': '南米德尔顿',
 'North Middleton': '北米德尔顿',
 'Bayside Plant': '湾岸工厂',
 'Yamate Town Ruins': '山手町遗迹',
 'Theater Hall': '剧场大厅',
 'Nibashi Business District': '二桥商业区',
 'Daiba Canal Bridge': '台场运河桥',
 'Central Tower': '中央塔',
 'Middleton Northwest Zone': '米德尔顿西北区',
 'Riverside Complex': '河畔综合大楼',
 'Central Office District': '中央办公区',
 'Storage Tank': '储罐区',
 'River Research Institute': '河川研究所',
 'Middleton Northeast Zone': '米德尔顿东北区',
 'Palace': '宫殿',
 'Nakasu Broadway': '中洲百老汇',
 'Central Twin Buildings': '中央双子大楼',
 'Middleton Southeast Zone': '米德尔顿东南区',
 'Triangle Tower': '三角塔',
 'Medical Center': '医疗中心',
 'Middleton Southwest Zone': '米德尔顿西南区',
 'Nakasu Alley': '中洲小巷',
 'Old Middleton Dome': '旧米德尔顿巨蛋',
 'Neo-Middleton Dome': '新米德尔顿巨蛋',
 'Central District Housing': '中央区住宅街',
 'Vacant Lot': '空地',
 'Town Center': '镇中心',
 'Town Fringes': '镇郊',
 **{f'Training Facility [Floor {i}] ': f'训练设施 [{i}层]' for i in range(1, 14)},
}

# ── 素材 / 效果名（属性口径跟系统文本一致）──────────────────
MATERIAL = {
 'Contamination Resistance': '污染抗性',
 'Sleep Resistance': '睡眠抗性',
 'Paralysis Resistance': '麻痹抗性',
 'Seal Resistance': '封印抗性',
 'Panic Resistance': '恐慌抗性',
 'Darkness Resistance': '黑暗抗性',
 'Virus Resistance': '病毒抗性',
 'IN.KO Resistance': '即死抗性',
 'Fire Resistance': '火属性抗性',
 'Water Resistance': '水属性抗性',
 'Wind Resistance': '风属性抗性',
 'Earth Resistance': '土属性抗性',
 'Null Resistance': '无属性抗性',
 'HP Up': 'HP提升',
 'SP Up': 'SP提升',
 'Song Power Up': '歌力提升',
 'Stamina Up': '耐力提升',
 'Knowledge Up': '知识提升',
 'Divinity Up': '神力提升',
 'Technique Up': '技巧提升',
 'Vitality Up': '活力提升',
 'Accuracy Up': '命中率提升',
 'Evasion Up': '回避率提升',
 'Critical Rate Up': '暴击率提升',
 'Earned EXP Up': '获得EXP提升',
 'Earned EP Up': '获得EP提升',
 'HP Lv. UP Modifier': 'HP升级修正',
 'SP Lv. UP Modifier': 'SP升级修正',
 'Singing Lv. UP Modifier': '歌力升级修正',
 'Stamina Lv. UP Modifier': '耐力升级修正',
 'Knowledge Lv. UP Modifier': '知识升级修正',
 'Divinity Lv. UP Modifier': '神力升级修正',
 'Technique Lv. UP Modifier': '技巧升级修正',
 'Vitality Lv. UP Modifier': '活力升级修正',
 'HP Auto-Recovery ': 'HP自动回复',
 'SP Auto-Recovery ': 'SP自动回复',
 'Voltage UP': '电压提升',
 'Physical damage Up': '物理伤害提升',
 'Physical Damage Up': '物理伤害提升',
 'Physical resistance Up': '物理抗性提升',
 'Magical damage Up': '魔法伤害提升',
 'Magical Damage Up': '魔法伤害提升',
 'Magical resistance Up': '魔法抗性提升',
 'HP Absorb Defense': 'HP吸收防御',
 'SP Absorb Defense': 'SP吸收防御',
 'Resist HP Break': 'HP破坏抗性',
 'Resist SP Break': 'SP破坏抗性',
 'Limiter Removal': '限制器解除',
}


# ── 怪物名（神话专名用通行中译；描述性名字意译）────────────
MONSTER = {
 'Abas': '阿巴斯', 'Achilles': '阿喀琉斯', 'Admiral Lancer': '枪兵将官',
 'Aello': '埃洛', "Al-mi'raj": '独角兔', 'Albion': '阿尔比恩',
 'Ammit': '阿米特', 'Amphisbaena': '双头蛇', 'Anansi': '阿南西',
 'Ananta': '阿难陀', 'Ancient Dragon': '远古龙', 'Anubis': '阿努比斯',
 'Apsaras': '飞天女', 'Arachne': '阿拉克涅', 'Arcadian Brute': '阿卡迪亚蛮兽',
 'Archangel': '大天使', 'Archdragon': '龙王', 'Astaroth': '阿斯塔罗特',
 'Astral Beast': '星界兽', 'Auraune': '曼德拉草妖', 'Avatar of Destruction': '破灭化身',
 'Awakened Aria': '觉醒艾莉亚', 'Awakened Blare': '觉醒Blare',
 'Aži Dahāka': '阿日达哈卡', 'Baal': '巴尔', 'Balrog': '炎魔',
 'Barreleye': '管眼鱼', 'Baryonyx': '重爪龙', 'Basilisk': '蛇怪',
 'Beast': '野兽', 'Blattaria ': '蜚蠊', 'Blood Fang': '血牙',
 'Blood Lancer': '血枪兵', 'Blood Mantis': '血螳螂', 'Blue Mayfly': '青蜉蝣',
 'Blue Scorpion': '青蝎', 'Bone Crusher': '碎骨者', 'Brevet': '名誉衔',
 'Briwen Turtle': '布里文龟', 'Budgerigar': '虎皮鹦鹉', 'Caim': '盖因',
 'Calamitous Eagle': '灾祸之鹰', 'Caliginous Bat': '幽暗蝠',
 'Cannibal Mayfly': '食人蜉蝣', 'Cannibal Shark': '食人鲨',
 'Carnage Walker': '杀戮行者', 'Carnivorous Larva': '食肉幼虫',
 'Ceryneian': '刻律涅牝鹿', 'Chaos': '混沌', 'Chaos ': '混沌',
 'Cherub': '智天使', 'Clione': '海天使', 'Colossal Insect': '巨型虫',
 'Corroded One': '侵蚀者', 'Cottingley Fairy': '柯汀莱妖精',
 'Crazed Predator': '狂乱掠食者', 'Crimson Insect': '深红虫',
 'Crom Cruach': '克罗姆·库拉赫', 'Cybele': '库柏勒',
 'Dark Mantis': '暗螳螂', 'Dead Emperor': '亡者皇帝', 'Demon Herald': '魔先驱',
 'Demon Mecha': '魔机兵', 'Deranged Predator': '错乱掠食者',
 'Devil Eater': '噬魔者', 'Devil Predator': '魔掠食者',
 'Devol Lizard': '德沃蜥', 'Doll Soldier': '人偶兵', 'Dominion': '主天使',
 'Double X': '双X', 'Dragonar': '龙骑兵', 'Dryad': '树精',
 'Dáinsleif': '达因斯莱夫', 'Eikþyrnir': '埃克锡尔尼尔', 'Enigma': '谜',
 'Eocaecilia': '始蚓螈', "Er'el": '埃雷尔', 'Evil Fish': '邪鱼',
 'Fafnir': '法夫纳', 'Fauves': '野兽群', 'Fenrir': '芬里尔',
 'Fiend': '恶鬼', 'Flauros': '弗劳洛斯', 'Flood Shark ': '洪流鲨',
 'Freyja': '弗蕾亚', 'Furfur': '弗尔弗尔', 'Gaia': '盖亚',
 'Garuda': '迦楼罗', 'Genesis Turtle': '创世龟', 'Giant Beetle': '巨甲虫',
 'Giant Calyptra': '巨吸血蛾', 'Giant Eagle': '巨鹰', 'Giant Fly': '巨蝇',
 'Giant Insect': '巨虫', 'Giant Mantis': '巨螳螂', 'Giant Mouse': '巨鼠',
 'Giant Vampire Bat': '巨吸血蝠', 'Giant Vermin': '巨害虫',
 'Gurangatch': '古兰加奇', 'Hag Caterpillar': '丑妪毛虫',
 'Hamadryad': '林中仙女', 'Hamelin': '哈梅恩', 'Hanuman': '哈奴曼',
 'Harbinger': '先兆者', 'Harvest Guardian': '丰收守护者',
 'Hell Insect': '狱虫', 'Hell Vermin': '狱害虫', 'Hellhound': '地狱犬',
 'Heretic ': '异端者', 'Hest Mouse': '赫斯特鼠', 'Hexe Salpa': '魔女樽海鞘',
 'Horned Beetle': '独角仙', 'Houri': '天堂仙女', 'Hræsvelgr': '赫拉斯瓦尔格',
 'Hunger Wolf': '饥饿之狼', 'Impure God Veles': '秽神韦莱斯',
 'Insect': '虫', 'Jormungand': '约尔孟甘德', 'Jörmungandr': '耶梦加得',
 'Kaiser Dragon': '皇帝龙', 'Kali': '迦梨', 'Kangada': '康加达',
 'Khepera': '凯布利', 'King Lizard': '蜥蜴王', 'Kodama': '木灵',
 'Kolossal Wächter': '巨像守卫', 'Kornmöhme': '谷母', 'Koropokkuru': '蜂斗菜精',
 'Kürten': '库尔滕', 'Lancer': '枪兵', 'Larva': '幼虫',
 'Leedsichthys': '利兹鱼', 'Leptocephalus': '柳叶鳗',
 'Lilith': '莉莉丝', 'Lone Wolf': '孤狼', 'Lorelei': '罗蕾莱',
 'Mab': '玛布', 'Magniventris': '大腹兽', 'Mecha Cerberus': '机械刻耳柏洛斯',
 'Mecha Dragon': '机械龙', 'Mello': '梅洛', 'Mercury Moth': '水银蛾',
 'Meretseger': '梅尔塞盖尔', 'Mictlantecuhtli': '米克特兰特库特利',
 'Mokkurkalfe': '莫库尔卡尔菲', 'Moloch': '摩洛',
 'Moru Bulrush': '莫鲁香蒲', 'Mushussu': '穆修胡修', 'Myrmecoleon': '蚁狮',
 'Naga': '那伽', 'Neamhain': '涅温', 'Nightfalter': '夜蛾',
 'Noble Insect': '贵族虫', 'Norn': '诺伦', 'Níðhöggr': '尼德霍格',
 'Ocyanate': '奥基亚涅', 'Ogre Rat': '食人魔鼠', 'Ophanim': '座天使',
 'Pabilsag': '帕比尔萨格', 'Pachyrhachis': '厚棘蛇', 'Pale Larva': '苍白幼虫',
 'Peryton': '佩里顿', 'Phantom': '幻影', 'Phantom Butterfly': '幻蝶',
 'Phoenix': '凤凰', 'Pixie': '小妖精', 'Predator': '掠食者',
 'Psyche': '普赛克', 'Queen Igrai': '伊格莱女王', 'Rabuka': '拉布卡',
 'Rafflesia': '大王花', 'Red Beetle': '红甲虫', 'Redcap': '红帽子',
 'Ring Dragon': '环龙', 'Ruby Mantis': '红宝石螳螂', 'Rudra Creare': '楼陀罗创生体',
 'Salamander': '火蜥蜴', 'Sarracenia': '瓶子草', 'Satanael': '撒旦奈尔',
 'Scordatura': '变格调弦', 'Scorpion': '蝎', 'Scourge Dragon': '灾厄龙',
 'Sea Demon': '海魔', 'Sekhmet': '塞赫麦特', 'Selachii': '鲨类',
 'Seraph': '炽天使', 'Serket': '塞尔凯特', 'Shade Minion': '暗影仆从',
 'Shredder': '碎裂者', 'Soul Eater': '噬魂者', 'Spinne': '蛛',
 'Steel Bug': '钢铁虫', 'Steel Insect': '钢铁昆虫', 'Strange Dragon': '异龙',
 'Strophanthus': '羊角拗', 'Succubus': '魅魔', 'Sugriva': '须羯哩婆',
 'Tailcoater': '燕尾服客', 'Taipan': '太攀蛇', 'Tawny Beast': '褐毛兽',
 'Titanfoot': '巨足兽', 'Titania': '缇坦妮雅', 'Tobikura': '飞仓',
 'Twin Lancer': '双枪兵', 'Tyrant God Ares': '暴君神阿瑞斯',
 'Upli Guardian': '乌普利守卫', 'Utgaroa': '乌特加罗', 'Utukku': '乌图库',
 'Vandal': '破坏者', 'Vepar': '威沛', 'Verethragna': '韦雷斯拉格纳',
 'Vermillion': '朱红', 'Vonara': '沃娜拉', "Warped Kamapua'a": '扭曲卡马普阿',
 'Édaín': '埃丁',
}

# ── 技能 / 被动名 ────────────────────────────────────────────
# 只写「词根」。带 "+"、"+ +" 的强化档位由 resolve() 自动派生，
# 说明文里已经有译法的（b4_gloss 挖出的 116 条）也由 resolve() 自动沿用。
SKILL = {
 '100% E Skill Accuracy': 'E技能命中率100%', '100% Skill Accuracy': '技能命中率100%',
 'Absolute Accuracy': '绝对命中', 'Absolute Evasion': '绝对回避',
 'Absorb': '吸收', 'Abyss': '深渊',
 'Accuracy Up': '命中率提升', 'Accuracy ・Evasion Up': '命中率・回避率提升',
 'Acquisition Support': '获取支援', 'Acrobatics Master': '杂技大师',
 'Aerial Slumber': '空中沉眠',
 'All Attack Skill Power Up': '全攻击技能威力提升',
 'All Elemental Attack Negation': '无效化全属性攻击',
 'All Status Abnormality Damage Up': '所有状态异常伤害提升',
 'All status abnormality damage Up': '所有状态异常伤害提升',
 'All status abnormalities are negated': '无效化所有状态异常',
 'Allegro Giocoso': '欢快快板', 'Alluring Aroma': '魅惑香氛',
 "Angel's Secret": '天使的秘密', 'Angelic Voice': '天使之声',
 'Ankh Sword': '安卡之剑', 'Annihilate': '歼灭',
 'Anti-Static Spray': '抗静电喷雾', 'Anti-Static Tissue': '抗静电纸巾',
 'Antidote Spray': '解毒喷雾', 'Antitoxin': '解毒剂',
 'Antiviral Medication': '抗病毒药', 'Antiviral Spray': '抗病毒喷雾',
 'Aqua Blaze': '水炎', 'Aqua Breath': '水之吐息',
 'Arc En Ciel': '彩虹', 'Arc Ray': '弧光', 'Ares Stone': '阿瑞斯之石',
 'Aromatic Candle': '香氛蜡烛', 'Athena Spell': '雅典娜咒文',
 'Attack Weapon': '攻击武器', 'Auto-Guard': '自动防御', 'Auto-Guard Up': '自动防御提升',
 'Avalanche': '雪崩', 'Balance Assist': '平衡辅助',
 'Battlefield Rhapsody': '战场狂想曲', 'Baïonnette': '刺刀',
 'Black Mist': '黑雾', 'Blood Howl': '血啸', 'Blooden': '布洛登',
 'Blue Holy Water': '蓝圣水', 'Bonus Heaven': '奖励天堂',
 'Bonus Paradise': '奖励乐园', 'Bonus Shangri-La': '奖励香格里拉',
 'Bonus Tengoku': '奖励天国', 'Broil': '炙烤',
 'Caffeinated Drink': '含咖啡因饮料', 'Caffeine Spray': '咖啡因喷雾',
 'Calamity': '灾厄', 'Cataclysm': '大灾变',
 'Chain Skill Up': '连锁技能提升', 'Chain Strike': '连锁打击',
 'Chaos Flame': '混沌之炎', 'Charm': '魅惑', 'Claw': '爪击',
 'Clear Eyedrop Spray': '清凉眼药喷雾', 'Clear Eyedrops': '清凉眼药水',
 'Clear Field': '净场', 'Complete Steal Defense': '完全防盗',
 'Cosmic Fan': '宇宙战扇', 'Crimson Schnell': '深红疾速',
 'Critical Assist': '暴击辅助',
 'Critical Rate Up': '暴击率提升', 'Critical rate Up': '暴击率提升',
 'Crush': '粉碎', 'Cure-All Spray': '万能喷雾',
 'Cursed Eye': '诅咒之眼', 'Cursed Touch': '诅咒之触',
 'Cyclone': '气旋', 'Cyclone Wave': '气旋波',
 'Damage Modification A': '伤害修正A', 'Damage Modification B': '伤害修正B',
 'Dark Impact': '暗黑冲击', 'Dark Whisper': '暗语',
 'Death Crush': '死亡粉碎', 'Death  Crush': '死亡粉碎', 'Death Howl': '死亡咆哮',
 'Defense Bonus': '防御加成', 'Defense Guardian': '防御守护',
 'Defile': '玷污', 'Destruction': '破坏', 'Diet Master': '节食大师',
 'Digestive Fluid': '消化液', 'Dispel Powder': '驱散粉', 'Dispel Spray': '驱散喷雾',
 'Dissolve': '溶解', 'Drain': '吸取', 'Drift': '漂移',
 'Drop Rate Up': '掉落率提升', 'Drop RateUp': '掉落率提升',
 'Dry Sonata': '枯燥奏鸣曲',
 'E Skill Defense Bonus': 'E技能防御加成', 'E Skill Evasion': 'E技能回避',
 'E Skill Guardian': 'E技能守护', 'E Skill Negation Chance': 'E技能无效化概率',
 'E Skill Offense-Defense Up': 'E技能攻防提升',
 'E Skill・ Defense Power Up': 'E技能・防御力提升',
 'Earth Breath': '大地吐息', 'Earth Crush': '大地粉碎',
 'Earth Element Up': '土属性提升', 'Earthquake': '地震',
 'Efflorescence': '绽放', 'Elegant Perfume': '优雅香水',
 'Elixir Bottle': '灵药瓶', 'Empress Domain': '女帝领域',
 'Energy Assist': '能量辅助', 'Energy Break': '能量破坏',
 'Energy Burst': '能量爆发', 'Energy Drain': '能量吸取',
 'Enervate': '衰弱', 'Ensnare': '缠绕', 'Eruption': '喷发',
 'Eternal Quintet': '永恒五重奏', 'Evasion Up': '回避率提升',
 'Explosion': '爆炸', 'Explosive Love Song': '爆裂情歌',
 'Fast-Acting Protein': '速效蛋白质', 'Fierce Blow': '猛击',
 'Fighting Spirit Etude': '斗志练习曲', 'Final Symphony': '终焉交响曲',
 'Fire Breath': '火焰吐息', 'Fire Element Up': '火属性提升',
 'Fissure': '地裂', 'Five-Element Attacker': '五属性攻击者',
 'Five-Element Guardian': '五属性守护者',
 'Flame Arbalest': '火焰弩', 'Flame Bullet': '火焰弹', 'Flame Edge': '火焰刃',
 'Flare': '烈焰', 'Frost': '冰霜', 'Frost Blaze': '霜炎',
 'Gehenna': '欣嫩谷', 'Girls Fortissimo': '少女最强音',
 'Gospel Prayer': '福音祈祷', 'Grace Perfume EX': '优雅香水EX',
 'Grand Breath': '壮阔吐息', 'Grand Cross': '大十字',
 'Grand Crush': '壮阔粉碎', 'Grand Stream': '壮阔激流',
 'Graviton': '引力子', 'Gravity Blaze': '重力烈焰',
 'Great Eye': '巨目', 'Gust': '疾风',
 'HP & SP Up': 'HP＆SP提升', 'HP Auto-Recover': 'HP自动回复',
 'HP Recover': 'HP回复', 'HP Up': 'HP提升', 'HP Up 50': 'HP提升50',
 'Harmony': '和声', 'Hati': '哈提', 'Healing Mist': '治愈之雾',
 'Healing Support': '治疗支援', 'Hell Gazer': '地狱凝视',
 'High-Grade Aroma Oil': '高级香薰油', 'High-Grade Supplement': '高级营养剂',
 'Hit and Run': '打带跑', 'Holy Mist': '圣雾', 'Howling Storm': '咆哮风暴',
 'Hyaluronan Brew': '玻尿酸饮', 'Ice Wave': '冰波', 'Imbibe': '畅饮',
 'Inferno': '炼狱', "Insomniac's Lullaby": '失眠者摇篮曲',
 'Judgment': '审判', 'Kaiser Breath': '皇帝吐息', 'Landler': '连德勒舞曲',
 'Last Angel': '最后天使', 'Lavender Perfume': '薰衣草香水',
 'Life Elixir': '生命灵药', 'Lightning Bomb': '闪电炸弹', 'Loure': '卢尔',
 'Low Fuel Consumption Master': '低耗能大师', 'Lucerne Hammer': '琉森战锤',
 'Lure': '诱敌', 'Magic Weapon': '魔法武器',
 'Mic Assist': '音器辅助', 'Mic Strike': '音器打击', 'Mighty Breath': '强力吐息',
 'Mist Crush': '迷雾粉碎', 'Mist  Crush': '迷雾粉碎',
 'Morning Star': '晨星', 'Muspelheim': '穆斯贝尔海姆',
 'Negate All Status Abnormalities': '无效化所有状态异常',
 'Negate Contamination': '无效化污染', 'Negate Darkness & Panic': '无效化黑暗＆恐慌',
 'Negate Four-Element Damage': '无效化四属性伤害', 'Negate IN.KO': '无效化即死',
 'Negate Paralysis': '无效化麻痹', 'Negate Reversal': '无效化反转',
 'Negate Seal': '无效化封印', 'Negate Sleep': '无效化睡眠',
 'Negate Turn Delay & Reversal': '无效化回合延迟＆反转',
 'Negate Virus': '无效化病毒', 'Negate Wait Time Increase': '无效化等待时间增加',
 'Negation Guardian': '无效化守护', 'Neoclassical Metal': '新古典金属',
 'Nightmare': '噩梦', 'Noble Mist EX': '高贵之雾EX', 'Outbreak': '爆发',
 'Panacea': '万灵药', 'Paralyze': '麻痹', 'Paralyzing Mist': '麻痹之雾',
 'Particular E Skill Damage Down': '特定E技能伤害下降',
 'Particular E Skill Damage Up': '特定E技能伤害提升',
 'Particular E Skill Offense-Defense Up': '特定E技能攻防提升',
 'Particular Skill Damage Down': '特定技能伤害下降',
 'Particular Skill Damage Up': '特定技能伤害提升',
 'Particular Skill Offense-Defense Up': '特定技能攻防提升',
 'Perfect Guard': '完全防御', 'Perfume': '香水',
 "Philosopher's Remedy": '贤者灵药', 'Poison Mist': '毒雾',
 "Pop'n Requiem": '流行安魂曲', 'Power Drain': '力量吸取',
 'Precision Strike Assist': '精准打击辅助', 'Pressure': '压迫',
 'Pressure Burst': '压迫爆发', 'Priestess Miracle Cure': '巫女奇迹药',
 'Quarter Raid': '四分突袭', 'Qutuga': '库图加',
 'Radiant Phenomenon': '辉耀现象',
 'Range + Skill + Individual Power Up': '范围＋技能＋单体威力提升',
 'Ranged Attack (Individual) Damage Up': '远程攻击（单体）伤害提升',
 'Rare Steal Defense': '稀有防盗', 'Recover Effect Up': '恢复效果提升',
 'Recovery Skill & Effect Up': '恢复技能＆效果提升', 'Recovery Skill Up': '恢复技能提升',
 'Reduced Wait Time': '等待时间缩短', 'Refresh Seal': '清爽印章',
 'Resist Status Abnormalities': '状态异常抗性',
 'Resistance Filter α': '抗性滤镜α', 'Resistance Filter β': '抗性滤镜β',
 'Resistance Filter γ': '抗性滤镜γ', 'Resistance Filter δ': '抗性滤镜δ',
 'Resistance Guardian': '抗性守护', 'Resonance': '共鸣',
 'Resonant Breath': '共鸣吐息', 'Resurrection Light': '复活之光',
 'Revelation Cross': '启示十字', 'Revival Medicine': '复活药',
 'Roar': '咆哮', 'Rotting Breath': '腐臭吐息', 'Royal Drink DX': '皇家饮料DX',
 'S. Skill Up': 'S技能提升', 'SP Auto-Recover': 'SP自动回复',
 'SP Consumption Decrease': 'SP消耗减少', 'SP Consumption Down': 'SP消耗下降',
 'SP Recover': 'SP回复', 'SP Up': 'SP提升', 'SP Up 50': 'SP提升50',
 'SP restored when damaged': '受伤时回复SP',
 'Sacred Light': '神圣之光', 'Serenade Bomb': '小夜曲炸弹',
 'Serene Talisman': '宁静护符', 'Shock Wave': '冲击波',
 'Shock Wave Split': '冲击波分裂',
 'Skill Damage Negation Chance': '技能伤害无效化概率',
 'Skill Damage Up': '技能伤害提升', 'Skill Defense Bonus': '技能防御加成',
 'Skill Evasion': '技能回避', 'Skill Offense-Defense Up': '技能攻防提升',
 'Skill Power・ Defense Power Up': '技能威力・防御力提升',
 'Skyflower Fragrance': '天花香', 'Sleep Mist': '睡眠之雾',
 'Smash': '重击', 'Snipe Strike': '狙击', 'Solid Impact': '坚实冲击',
 'Song of Ruin': '毁灭之歌', 'Soothing Patch': '舒缓贴',
 'Soothing Spray': '舒缓喷雾', 'Soul Poetry': '灵魂诗篇',
 'Special Fanfare': '特别号角', 'Special Strike': '特殊打击',
 'Spike': '尖刺', 'Spin Attack': '旋转攻击', "Spirit's Breath": '精灵吐息',
 'Splash': '飞溅', 'Sports Drink': '运动饮料', 'Spotlight': '聚光灯',
 'Squall': '飑风', 'Steal Auto-Guard': '自动防盗', 'Steal Defense': '防盗',
 'Steal Rate Up': '盗取率提升', 'Steam Burst': '蒸汽爆发',
 'Stomp': '践踏', 'Storm': '风暴', 'Storm Gazer': '风暴凝视',
 'Super Mineral Supplement DX': '超级矿物补充剂DX',
 'Super Vitamin Supplement': '超级维生素剂', 'Support': '支援',
 'Surgence': '涌现', 'Tackle': '冲撞', 'Tech Greed': '技巧贪婪',
 'Terra Nova': '新大地', 'Third Melody': '第三旋律', 'Tidal Wave': '潮汐波',
 'Touch of Death': '死之触', 'Toxic Fog': '剧毒之雾', 'Tragedy': '悲剧',
 'Tricolor Sword': '三色剑', 'Trinity Breath': '三位一体吐息',
 'Turbulence': '乱流', 'Turn Start Voltage UP': '回合开始电压提升',
 'Turn Start Voltage Up': '回合开始电压提升',
 'Twin Melody': '双重旋律', 'Typhoon': '台风', 'Ultrasonic Wave': '超声波',
 'Victory Assistance': '胜利支援', 'Vitamin Drink': '维生素饮料',
 'Vitamin Supplement': '维生素剂', 'Void Blast': '虚空冲击',
 'Voltage Up': '电压提升', 'Warrior Arena': '战士竞技场',
 'Water Element Up': '水属性提升', 'Whirlwind': '旋风',
 'Wind Breath': '风之吐息', 'Wind Crush': '风之粉碎',
 'Wind Element Up': '风属性提升', 'Windstorm': '暴风',
 "Witch's Potion": '魔女药剂',
}


# ── 物品名 ──────────────────────────────────────────────────
# 装备名后缀（AG / EG / GF / DL / EL / TL / RL / SL / AL）是型号，保留原样。
ITEM = {
 "'The Horse Who Leapt Through Time' Pamphlet": '《穿越时空的马》宣传册',
 'Ability Slate': '能力石板', 'Accidental Art': '意外的艺术',
 'Acidic Liquid': '酸性液体', 'Activity Log': '活动日志',
 'Aged Map of Verdant Greenbelt': '翠绿地带古地图',
 'Aged Map of the Arid Wilderness': '干涸荒野古地图',
 'Agito': '阿吉托', 'Air Break': '裂空', 'Alexandrite': '亚历山大石',
 'Allgemein': '普遍', 'Amazing AG': '惊异 AG', 'Anat EG': '阿娜特 EG',
 'Ancient Moss': '远古苔藓', 'Ancient Writings': '远古文书',
 'Angel Monocle': '天使单片眼镜', 'Angel Ring': '天使指环',
 'Anise': '茴香', 'Anonymous Manager・Pince-Nez': '无名主席・夹鼻镜',
 'Apocalypse': '天启', 'Apollo EG': '阿波罗 EG',
 'Aquamarine Snow': '海蓝宝之雪', 'Arcana Barrier': '奥秘屏障',
 'Aria Report': '艾莉亚报告', 'Arid Wilderness Guide Map': '干涸荒野导览图',
 'Arid Wilderness Treasure Map': '干涸荒野藏宝图',
 "Arid Wilderness on Shank's Mare": '徒步干涸荒野',
 'Army Film': '军队胶片', 'Asherah EG': '阿舍拉 EG',
 'Asian Underwear': '亚洲风内衣', 'Astarte EG': '阿斯塔蒂 EG',
 'Asterism GF': '星芒 GF', 'Aurore Barricade': '曙光壁垒',
 'Auto Field': '自动力场', 'Auto-Guard Memory': '自动防御记忆',
 'Automne AG': '秋日 AG', 'Avenir': '未来', 'Axion': '轴子',
 'Axion Particle': '轴子粒子', 'Azure Holy Water': '天蓝圣水',
 'Bath Banana': '浴室香蕉', 'Bayside Plant Treasure Guide': '湾岸工厂寻宝指南',
 'Beam DL': '光束 DL', 'Beast Fang': '兽牙', 'Beast Film': '野兽胶片',
 'Beast Hunter': '猎兽者', 'Beautiful Fabric': '华美布料',
 'Beautiful Petal': '华美花瓣',
 'Behind the Developer - Volume 1': '开发者幕后 第1卷',
 'Behind the Developer - 2': '开发者幕后 第2卷',
 'Behind the Developer - 3': '开发者幕后 第3卷',
 'Behind the Developer - Volume 4': '开发者幕后 第4卷',
 'Bitter Fruit': '苦涩果实', 'Bizarre Insect Scales': '怪虫鳞片',
 'Black Crystal': '黑水晶', 'Black Gem': '黑宝石', 'Black Glasses Case': '黑色眼镜盒',
 'Black Jewel': '黑宝珠', 'Black Leather Cord': '黑皮绳',
 'Black Leather Notebook - First Half': '黑皮笔记本 上',
 'Black Leather Notebook - Second Half': '黑皮笔记本 下',
 'Black Phosphorus Wing': '黑磷之翼', 'Black Rock': '黑岩', 'Black Rubble': '黑碎石',
 'Black Strappy Shoes': '黑色绑带鞋', 'Blanch TL': '漂白 TL',
 'Blaze Field': '烈焰力场', 'Blaze Foil': '烈焰箔', 'Blaze RL': '烈焰 RL',
 'Blood Hall': '血之殿堂', 'Blood Ruby': '血红宝石', 'Blood Stone': '血石',
 'Blood-Rusted Handle': '血锈握柄', 'Bloodied Sheepskn': '血染羊皮',
 'Bloodlust': '嗜血', 'Blue Berry': '蓝色浆果',
 'Blue Collar Girl Case Files': '蓝领少女事件簿', 'Blue Cross': '蓝十字',
 'Blue Crust': '蓝壳', 'Blue Crystal': '蓝水晶', 'Blue Dolphin': '蓝海豚',
 'Blue Gem': '蓝宝石', 'Blue Jewel': '蓝宝珠', 'Blue Liquid': '蓝色液体',
 'Blue Rock': '蓝岩', 'Blue Rubble': '蓝碎石',
 'Book of Prophecy': '预言之书', 'Boxer Shorts': '平角裤',
 'Braided Bangs': '编发刘海', 'Braided Bun': '编发丸子头',
 'Braided Pigtails': '编发双马尾', 'Braids, Moé, and Me': '辫子、萌与我',
 'Brave Dance': '勇者之舞', 'Breeze EL': '微风 EL', 'Broken Blade': '断刃',
 'Bronze Hoof': '青铜蹄', 'Brown Crystal': '褐水晶', 'Brown Doll': '褐色人偶',
 'Brown Gem': '褐宝石', 'Brown Jewel': '褐宝珠', 'Brown Rock': '褐岩',
 'Brown Rubble': '褐碎石', 'Brutal Horn': '残暴之角', 'Butterfly Mask': '蝶形面具',
 'Caffeine Drink': '咖啡因饮料', 'Calamity Spike': '灾厄尖刺',
 'Camo Blur': '迷彩模糊', 'Cancel Memory': '取消记忆',
 'Cannon Barrier': '火炮屏障', 'Carapace AG': '甲壳 AG', 'Carnelian': '红玉髓',
 'Castle Balloon': '城堡气球', 'Casual Boots': '休闲短靴',
 'Cat Ear Hat': '猫耳帽', 'Cat Ears': '猫耳', 'Cat Skull Eyepatch': '猫骷髅眼罩',
 'Cave Exploration Guide': '洞窟探索指南', 'Cave Treasure Guide': '洞窟寻宝指南',
 'Chalk Thread': '白垩线', 'Chaos Field': '混沌力场',
 'Chaotic Particle': '混沌粒子', 'Chaotic Piece': '混沌碎片',
 'Chartreuse Jupiter': '嫩绿木星', 'Chic Booties': '雅致短靴',
 'Chipped Tooth': '缺角之牙', 'Chromatin': '染色质', 'Chrome Square': '铬方块',
 'Circle SL': '圆环 SL', 'Clearview Core': '澄明核心', 'Cleaver': '砍刀',
 'Clover Hairpin': '四叶草发夹', 'Club Particle': '梅花粒子', 'Coin': '硬币',
 'Coke-Bottle Glasses': '瓶底眼镜', 'Colored Pencil Set': '彩色铅笔套装',
 'Colorless Shell': '无色外壳', 'Commandments!': '戒律！',
 'Compass of Memories': '记忆罗盘', 'Concentrated Core': '浓缩核心',
 'Contaminated Seed': '污染种子', 'Coronet': '小冠冕', 'Cosplay Soul': '角色扮演之魂',
 'Craftsman Hardhead': '工匠硬头盔', 'Crescent Moon': '新月',
 'Crest SL': '纹章 SL', 'Crimson Petal': '深红花瓣', 'Crimson Roll': '深红卷轴',
 'Crimson Wire': '深红丝线', 'Cross AL': '十字 AL', 'Cross Bone': '交叉骨',
 'Cross Clover': '十字四叶草', 'Crown Film': '王冠胶片', 'Crystal Case': '水晶盒',
 'Crystal Fragment': '水晶碎片', 'Curled Pigtails': '卷发双马尾',
 'Cursed Egg': '诅咒之卵', 'Cursed Treasure': '诅咒宝物',
 'Dagger GF': '短剑 GF', 'Damascus': '大马士革钢',
 'Dance Choreography Notebook': '舞蹈编排笔记', 'Danger Case': '危险箱',
 'Dark Matter': '暗物质', 'Dark Red Fang': '暗红之牙', 'Darkness Barrier': '黑暗屏障',
 'Daybreak Seed': '破晓种子', 'Daytime on Halloween': '万圣节的白天',
 'Dealing With the Mentally Broken': '与心碎者相处',
 "Death God's Scythe": '死神之镰', 'Deep Ocean Water': '深海水',
 'Deep Valley Tea': '深谷茶', 'Defense SL': '防御 SL',
 'Demon-Sealing Spell': '封魔咒', 'Designer Wallet': '名牌钱包',
 'Diable Sang': '恶魔之血', 'Diamond': '钻石', 'Diamond (?) Cross': '钻石（？）十字',
 'Diamond Hairpin': '钻石发夹', 'Diamond Particle': '方块粒子',
 'Dione EG': '狄俄涅 EG', 'Disorder Memory': '混乱记忆',
 'Divine Lance': '神圣长枪', 'Divine Seal': '神圣印记',
 "Djinni's Breath": '魔神之息', 'Doll Fragment': '人偶碎片',
 'Doomed Town': '末日之镇', 'Dragon AG': '飞龙 AG', 'Dragon Egg': '龙卵',
 'Dragon Emblem': '龙纹章', 'Dragon God Scales': '龙神鳞',
 'Dragon Hunter': '屠龙者', 'Dragon Lance': '龙枪', 'Dragon Tamer': '驯龙者',
 'Dragon Thief': '盗龙者', 'Dragon Wing Membrane': '龙翼膜',
 'Dried Clay': '干燥黏土', 'Dropped Sketchbook': '掉落的速写本',
 'Dusty Halo': '蒙尘光环', 'Dynamite Sash': '炸药腰带',
 'Déesse Larme': '女神之泪', 'Eagle Feather': '鹰羽', 'Earth Gem': '土宝石',
 'Earth Shaker': '撼地者', 'Eighth Graders [April Issue]': '八年级生 [四月号]',
 'Einphantom': '幻影一号', 'Electron Barricade': '电子壁垒',
 'Emerald': '祖母绿', 'Emerald Fragment': '祖母绿碎片',
 'Empty Plastic Bottle': '空塑料瓶', 'Enamel Cord': '漆皮绳',
 'Engagetia': '婚约之证', 'Eos EG': '厄俄斯 EG', 'Erebos EG': '厄瑞玻斯 EG',
 'Eternal Leaf': '永恒之叶', 'Excalibur': '断钢圣剑',
 'Exotic Film': '异国胶片', "Explorer's Cave Map": '探险家洞窟地图',
 'Extra Light': '特轻', 'Eyepatch': '眼罩', 'Eärendil': '埃雅仁德尔',
 'Face Mask': '面膜', 'Faintly Contaminated Husk': '微污染外壳',
 'Fairy Tears': '妖精之泪', 'Fairy Wing': '妖精之翼',
 'False Eyelashes': '假睫毛', 'Fang': '獠牙', 'Fantasy Field': '幻想力场',
 'Favorite Lighter': '心爱的打火机', 'Favorite Rolling Pin': '心爱的擀面杖',
 'Feather Case': '羽毛盒', 'Feminine Beret': '女式贝雷帽',
 'Fertile Mud': '沃泥', 'Final Strike': '最后一击', 'Finbrain': '鳍脑',
 'Firmament Gem': '苍穹宝石',
 'Five Little Piggies Picture Book': '五只小猪绘本',
 'Flower Maritime': '海之花', 'Flowery Princess': '花之公主',
 'Fogbow AG': '雾虹 AG', 'Forbidden Fruit': '禁果', 'Foster Core': '培育核心',
 'Fragrant Fluid': '芳香液', 'Frilly Holiday': '荷叶边假日',
 'From Your Senior to All of You': '前辈致各位', 'Fuuma': '风魔',
 'Gattling Fist': '加特林铁拳', 'Genesis Feather': '创世之羽',
 'Genetic Information': '遗传信息', 'Giant Eagle Wing': '巨鹰之翼',
 'Giant Pollen': '巨型花粉', 'Giant Tail': '巨尾',
}

ITEM2 = {
 'Devil Eater': '噬魔者', 'Glass Wing': '玻璃之翼', 'Glasses Catalog': '眼镜图册',
 'Glory Barrier': '荣耀屏障', 'Gold Uranus': '黄金天王星',
 'Golden Carrot': '黄金胡萝卜', 'Golden Drill': '黄金钻头',
 'Golden Kokeshi': '金色小芥子', 'Golden Straw': '黄金稻草',
 'Gothic Lolita Hat': '哥特萝莉帽', 'Grace AG': '优雅 AG',
 'Grand Slammer': '满贯重击', 'Grape Beads': '葡萄串珠',
 'Gravity Slate': '重力石板', 'Green Crystal': '绿水晶', 'Green Gem': '绿宝石',
 'Green Jewel': '绿宝珠', 'Green Moss': '绿苔', 'Green Rock': '绿岩',
 'Green Rubble': '绿碎石', 'Green Stripes': '绿条纹',
 'Groucho Glasses': '搞怪眼镜', 'Grídarvöl': '格莉德之杖', 'Hades': '哈迪斯',
 'Hair Clip': '发夹', 'Hairstylist Monthly [July Issue]': '发型师月刊 [七月号]',
 'Half Moon ML': '半月 ML', "Half-Up Braided 'Do": '半扎编发', 'Halo': '光环',
 'Hard Breaker': '硬破者', 'Hard-To-Obtain Herb': '稀有药草',
 'Hardened Fragment': '硬化碎片', 'Harmonics Disc': '和声唱片',
 'Harmony Cord': '和声绳', 'Healing Converter': '治疗转换器',
 'Heart & Cross': '心与十字', 'Heart Barrier': '心之屏障',
 'Heart Headband': '心形发带', 'Heart Paint': '心形彩绘',
 'Heart Particle': '红心粒子', 'Heart Tiara': '心形头冠',
 'Heartful Beads': '暖心串珠', 'Heat Haze Wing': '热浪之翼',
 "Heaven's Tapestry": '天界织锦', 'Heavenly Raiment': '天衣',
 'Heavy Spider Thread': '粗蛛丝', 'Hell Fang': '地狱之牙',
 'Hermes EG': '赫尔墨斯 EG', 'Heroic Beard': '英雄胡须', 'Heroic Horns': '英雄之角',
 'Hestia EG': '赫斯提亚 EG', 'Hexe Barrier': '魔女屏障',
 'Hidden Blaster': '隐匿爆破枪', 'Hide Stalker': '潜行者',
 'Hide-Seeker': '寻踪者', 'High Difficulty Workbook': '高难度习题集',
 'High Difficulty Workbook 2': '高难度习题集 2', 'High Pigtails': '高双马尾',
 'High Tension Case': '高涨情绪箱', 'High Tops': '高帮鞋',
 'High-Flying Kite': '高飞风筝', 'Highly Toxic Seed': '剧毒种子',
 'Highwind': '高空之风', 'Hiring Notice': '招聘启事',
 'Hollow Horn Fragment': '空心角碎片', 'Holy Water of Fate': '命运圣水',
 'Hoodie': '连帽衫', 'Hotel Amenity Shaving Razor': '酒店一次性剃须刀',
 'How to Walk North Middleton': '北米德尔顿漫步指南',
 'How to Walk the Arid Wilderness': '干涸荒野漫步指南',
 'How to Walk the Bayside Plant': '湾岸工厂漫步指南',
 'How to Walk the Skyscraper Shelter': '摩天避难所漫步指南',
 'How to Walk the Verdant Greenbelt': '翠绿地带漫步指南',
 'Hyper Saw': '高速锯', 'Ice-Cold Beer': '冰镇啤酒', 'Idea Field': '灵感力场',
 'Immortal Pure Wing': '不朽净翼', 'Imperial Wrath': '帝王之怒',
 'Indigo Neptune': '靛蓝海王星', 'Inferior Mineral': '劣质矿石',
 'Inferno Clay': '炼狱黏土', 'Infinity Sharp Fang': '无限利牙',
 'Information on the Dragon': '关于龙的情报', 'Iolight': '堇光石',
 'Iris GF': '鸢尾 GF', 'Iron Gear': '铁齿轮', 'Iron Pole': '铁棒',
 'Jariimaruufu': '贾里马鲁夫', 'Jet-Black Egg': '漆黑之卵',
 'Jet-Black Flame': '漆黑之炎', 'Joker Ribbon': '小丑缎带',
 'Jumbo Juice': '巨杯果汁', 'Jumeaux Lien': '双子之链',
 'Kachou Fuugetsu': '花鸟风月', 'Kaiser Sword': '皇帝之剑',
 'Kanadeko Report': '奏子报告', 'Kewpie Beads': '丘比串珠',
 "King's Bones": '王之骸骨', "King's Tail": '王之尾',
 'Kung-Fu Sandals': '功夫凉鞋', 'Kung-Fu Wear': '功夫服',
 'Kunoichi Costume': '女忍者装', "Kunoichi's Sandals": '女忍者草履',
 'Kyouka Report': '响歌报告', 'Laboratory Cover Glass': '实验室盖玻片',
 'Laboratory Flask': '实验室烧瓶', 'Laboratory Pestle': '实验室研杵',
 'Lady Heaven': '天堂淑女', 'Land Pearl': '陆珍珠', 'Large Egg': '大颗卵',
 'Large Kelp': '大海带', "Large Snake's Scale": '巨蛇鳞',
 'Latest Hats Catalog': '最新帽子图册', 'Lava Barrier': '熔岩屏障',
 'Leaf Cross': '叶形十字', 'Legend of the Sexy Ninjutsu': '香艳忍术传',
 'Lenno Glass': '莱诺玻璃', 'Life Converter': '生命转换器',
 'Light Blade': '光之刃', 'Light Green Seawater': '浅绿海水',
 'Light Matter': '光物质', 'Lime Swage': '青柠模具',
 'Little Black Undergarments': '小黑内衣',
 "Little Kitty's Big Adventure": '小猫咪大冒险', 'Living Tail': '活体尾巴',
 'Loli Soldier Sailor Luna': '萝莉战士水手露娜',
 'Long Black Hair': '黑色长发', 'Long Wavy Hair': '波浪长发',
 'Loose Braid': '松散辫子', 'Lost Item': '遗失物',
 'Loyal Particle': '忠诚粒子', 'Luna Break': '破月',
 'MC Beauty School Handbook': 'MC美容学校手册',
 'MC Beauty School Textbook': 'MC美容学校教材',
 'Mage Spice': '魔法师香料', 'Magic Slate': '魔法石板', 'Magic Staff': '魔法杖',
 "Magical Beast's Blood": '魔兽之血', 'Magical Stone Fragment': '魔石碎片',
 'Magnet AML': '磁力 AML', 'Magnet Beads': '磁石串珠',
 "Maid's Apron": '女仆围裙', "Maid's Headdress": '女仆头饰',
 "Maid's Kitchen Knife": '女仆菜刀', 'Majestic Trail': '威严之迹',
 'Major Crest': '大纹章', 'Maple Syrup': '枫糖浆',
 'Marine Look Underwear': '海军风内衣', 'Marine Snow': '海雪',
 'Mascot Strap': '吉祥物挂饰', 'Mechanical Pencil of Victory': '胜利自动铅笔',
 'Megaphone of My Youth': '青春的扩音器', 'Melatonin': '褪黑素',
 'Melody Barrier': '旋律屏障', 'Melody Earring': '旋律耳环',
 'Metaflourescence': '超荧光', 'Meteoric Iron': '陨铁',
 'Middleton Education Anthology': '米德尔顿教育文集',
 'Middleton Snow Festival Pamphlet': '米德尔顿冰雪节宣传册',
 'Midnight Lance': '午夜之枪', 'Midnight Polka Dots': '午夜波点',
 'Mind Barrier': '精神屏障', 'Mineral Crystal': '矿物结晶',
 'Minimalist Beads': '极简串珠', 'Minor Crest': '小纹章',
 'Modest Boots': '素雅短靴', 'Moglight': '莫古之光', 'Monkey Hair': '猴毛',
 "Monkey's Claw": '猴爪', 'Monotone Kitty-Cat': '黑白小猫',
 'Monotone Ribbon': '黑白缎带', 'Monster Design Gallery': '怪物设定画集',
 'Monthly Ribbon-chan [October Issue]': '月刊缎带酱 [十月号]',
 'Moonbow Tooth': '月虹之牙', 'Moondew Blade': '月露之刃',
 "Mother's Memorial Pendant": '母亲的纪念吊坠', 'Music Textbook': '音乐教材',
 'My Room Key': '我的房间钥匙', 'Mystery Hoof': '神秘之蹄', 'Mystic': '秘仪',
 'Naglfar': '纳吉尔法', 'Natural Loose Bun': '自然松丸子',
 'Navy Mercury': '藏青水星', 'Near-Mouth Mole': '嘴角痣',
 'Nene Report': '祢祢报告', 'Night King Jewel': '夜王宝珠',
 'Night Sword': '夜之剑', 'Nightglow Mineral': '夜光矿石', 'Nirvana': '涅槃',
 'Non-Non [March Issue]': '侬侬 [三月号]',
 'North Middleton Treasure Map': '北米德尔顿藏宝图', 'Nose Bandage': '鼻贴',
 'Oak Bark': '橡树皮', 'Oak GF': '橡木 GF', 'Obsidian': '黑曜石',
 'Oddly Fragrant Nectar': '异香花蜜', 'Old Camera': '旧相机',
 'Old Sheepskin': '旧羊皮', 'Old Verse Maiden Boots・Momoka': '旧歌姬短靴・桃香',
 'Old Verse Maiden Outfit・Sailor': '旧歌姬服・水手',
 'Opened Cigarette Pack': '开封的烟盒', 'Oracle Fragment': '神谕碎片',
 'Orichalcum': '奥利哈钢', 'Oshamajo Fasola': '小魔女法索拉',
 'Otanko・Nurse [Spring Issue]': '傻大姐・护士 [春季号]',
 'Otoha Report': '音羽报告', 'Pale Green Fruit Juice': '淡绿果汁',
 'Paper Airplane': '纸飞机', 'Partizan': '长柄斧枪',
 "Pattern Developer's Monologue Data": '型纸设计师独白数据',
 'Peachtaro [Winter Issue]': '桃太郎 [冬季号]', 'Pearl of Wisdom': '智慧之珠',
 'Pedipalp Fragment': '触肢碎片', 'Pentacle Jewel': '五芒星宝珠',
 'Perfect Barrier': '完美屏障', 'Phantasmic Jewel': '幻梦宝珠',
 'Phi GF': '斐 GF', "Philosopher's Stone": '贤者之石',
 'Piece of Lapis Lazuli': '青金石碎块', 'Pigtails': '双马尾',
 'Pile Striker': '打桩机', 'Pink Coral Monocle': '粉珊瑚单片镜',
 'Pink Ribbon Teddy Bear': '粉缎带泰迪熊', 'Pink Rose Girl': '粉玫瑰少女',
 'Pink Slippers': '粉色拖鞋', 'Pink Sneakers': '粉色运动鞋',
 'Pink Sunglasses': '粉色墨镜', 'Pixie Cut': '精灵短发',
 'Platinum Empress Eye': '铂金女帝之眼', 'Poisonous Insect Fang': '毒虫之牙',
 'Poisonous Powder': '毒粉', 'Police Force Casualties': '警队伤亡记录',
 'Police Report': '警方报告', 'Pomade': '发油', 'Ponytail': '马尾',
 'Potato': '土豆', 'Power Converter': '力量转换器', 'Power Cord': '力量绳',
 'Precious Handkerchief': '珍贵手帕', 'Precious Letter': '珍贵的信',
 'Pretty Jersey': '俏丽运动服', 'Primordial Garment': '原初衣装',
 "Prince's Deadly Toxin": '王子的剧毒', "Pro-Wrestler's Friend": '摔角手之友',
 'Proper Girl': '端庄少女', 'Psyclone': '灵旋', 'Puce Ribbon': '暗红缎带',
 'Pumpkin Denim': '南瓜牛仔', 'Pumpkin Hat': '南瓜帽',
 'Punk Girls [February Issue]': '朋克少女 [二月号]',
 'Pure Whilte Slough': '纯白蜕皮', 'Pure White Underwear': '纯白内衣',
 "Qliphoth's Sap": '克利佛树液', 'Quality Snakeskin': '优质蛇皮',
 'Quincrane': '昆克莱恩', 'Rad Student Cap': '炫酷学生帽',
 'Rainbow Barrier': '彩虹屏障', 'Rainbow Crystal': '彩虹水晶',
 'Rainbow Gem': '彩虹宝石', 'Rainbow Insect Scales': '彩虹虫鳞',
 'Rainbow Jewel': '彩虹宝珠', 'Rainbow Rock': '彩虹岩',
 'Rainbow Rubble': '彩虹碎石', 'Rare Blue Flower': '稀有蓝花',
 'Rare Jewel': '稀有宝珠', 'Reaction to Outfit': '对服装的反应',
 'Red Berry': '红色浆果', 'Red Crust': '红壳', 'Red Crystal': '红水晶',
 'Red Gem': '红宝石', 'Red Hall': '红之殿堂', 'Red Jewel': '红宝珠',
 'Red Monkey Hair': '红猴毛', 'Red Rock': '红岩', 'Red Rubble': '红碎石',
 'Red Seed': '红色种子', 'Regarding the Plant': '关于工厂的报告',
 'Revolver Cannon': '转轮炮', 'Rhythmical Case': '律动箱',
 'Ribbon Flower': '缎带花',
}

ITEM3 = {
 'Riize Hertz': '莱兹赫兹', 'Romance of the 3.5 Kingdoms': '三点五国演义',
 'Rose Lingerie': '玫瑰内衣', 'Round Glasses': '圆框眼镜',
 'Rugbrid': '拉格布里德', 'Rune Film': '符文胶片', 'Rune Slicer': '符文切割者',
 'Rune Strap': '符文挂饰', 'Russian Takoyaki': '俄罗斯章鱼烧',
 'Sacred Sword Fragment': '圣剑碎片', 'Sage Seal': '贤者印记',
 'Sagesse AG': '睿智 AG', 'Sailor Mini-One Piece': '水手迷你连衣裙',
 'Sap of Life': '生命树液', 'Scale of Genesis': '创世之鳞',
 'Scales of Seiran': '青岚之鳞', 'Scarlet Fruit': '绯红果实',
 'Scarlet Mars': '绯红火星', 'Selene EG': '塞勒涅 EG',
 'Sephiroth Jewel': '生命树宝珠', 'Sephiroth Leaf': '生命树之叶',
 'Seraph Reward': '炽天使的报酬', 'Servant Guide': '仆从指南',
 'Servant Guide 2': '仆从指南 2', 'Seven Raid Barrier': '七重突袭屏障',
 'Shadow Barrier': '暗影屏障', 'Shadow Blaster': '暗影爆破枪',
 'Sharp Spike': '锐利尖刺', 'Sharp Tooth': '锐齿', 'Shield Film': '护盾胶片',
 'Shield Seal': '护盾印记', 'Short Hair': '短发', 'Side Ponytail': '侧马尾',
 'Sienna Saturn': '赭色土星', 'Silent Cross': '静默十字',
 'Silver Clay': '银黏土', 'Silver Earth': '银色大地',
 'Silver Figaro Chain': '银费加罗链', 'Silver Ornament': '银饰',
 'Silver Straw': '白银稻草', 'Simple Ribbon': '素色缎带',
 'Simple Underwear': '素色内衣', 'Skeleton Cross': '骷髅十字',
 'Skill Support Core': '技能支援核心', 'Sky Blue Snake': '天蓝之蛇',
 'Skyscraper Shelter Guide': '摩天避难所导览',
 'Skyscraper Shelter Map': '摩天避难所地图',
 'Skyscraper Shelter Top-Secret Map': '摩天避难所绝密地图',
 'Skyscraper Shelter Treasure Map': '摩天避难所藏宝图',
 'Sledgehammer': '大锤', 'Sleipnir': '斯莱普尼尔',
 'Snipe Blaster': '狙击爆破枪', 'Snow Lingerie': '雪色内衣',
 "Snow Queen's Earring": '雪之女王耳环', "Snow Queen's Hat": '雪之女王之帽',
 'Snow White Corolla': '白雪花冠', 'Snow-White Boots': '雪白短靴',
 'Snowy Cape Dress': '雪披连衣裙', 'Soccer Ball': '足球',
 'Soft Feather': '柔羽', 'Soldier Seal': '士兵印记', "Someone's Poem": '某人的诗',
 'Sorcière Seal': '女术士印记', 'Soul Sucker': '吸魂者', 'Soul of Doom': '毁灭之魂',
 'Spade Headband': '黑桃发带', 'Spade Particle': '黑桃粒子',
 'Spanner Seal': '扳手印记', 'Special Iron Case': '特制铁箱',
 'Special Mic Blueprints (F)': '特殊音器图纸（F）',
 'Special Mic Blueprints (FA)': '特殊音器图纸（FA）',
 'Special Mic Blueprints (G)': '特殊音器图纸（G）',
 'Special Mic Blueprints (H)': '特殊音器图纸（H）',
 'Special Mic Blueprints (S)': '特殊音器图纸（S）',
 'Speed Seal': '速度印记', 'Spiral Barrier': '螺旋屏障',
 'Spirit Barrier': '精灵屏障', 'Spirit Field': '精灵力场',
 'Spirit Particle': '精灵粒子', "Spirit's Cocoon": '精灵之茧',
 "Spirit's Leaf": '精灵之叶', 'Split Husk': '裂开的外壳',
 'Sports Sunglasses': '运动墨镜', 'Sporty Bob': '运动波波头',
 'Sporty Girl': '运动少女', 'Star Breaker': '碎星者', 'Star Film': '星辰胶片',
 'Star-Shaped Headband': '星形发带', 'Stardust Cord': '星尘绳',
 'Steel Carapace': '钢铁甲壳', 'Stink Oil': '恶臭油',
 'Strawberry Beads': '草莓串珠', 'Strike Driver': '打击驱动器',
 'Stun Breaker': '眩晕破坏者', 'Summer Resort Girl': '避暑地少女',
 'Sun Fragment': '太阳碎片', "Sunglasses Gang' Pamphlet": '墨镜团宣传册',
 'Suns of Sun': '太阳之子', 'Super Herbal・Really Healy': '超级草药・真的有效',
 'Suspicious Slime': '可疑黏液', 'Suspicious White Powder': '可疑白粉',
 'Sutra': '经文', 'Sweetly Styling': '甜美造型', 'Sylphide': '西尔菲德',
 'Tears of Immortality': '不死之泪', 'Technical Converter': '技巧转换器',
 'Teddy Bear Pochi': '泰迪熊波奇', 'Testament': '圣约书',
 'Tethys EG': '忒堤斯 EG', 'The Three Who Kill': '弑者三人组',
 'The Weapon From Friday the 13th?': '十三号星期五的凶器？',
 'Thick Dictionary・Kōji-Yen': '厚辞典・广辞苑',
 "Tomekichi's Autobiography": '留吉自传', 'Tonbogiri': '蜻蛉切',
 'Topaz': '黄玉', 'Torn Snakeskin': '撕裂的蛇皮', 'Torn Wing': '撕裂之翼',
 'Tournesol GF': '向日葵 GF', 'Track Girls': '田径少女',
 'Traditional Undergarments': '传统内衣',
 'Training Facility News 1': '训练设施简报 1',
 'Training Facility Report 2': '训练设施报告 2',
 'Training Facility Report 3': '训练设施报告 3',
 'Treasure Location Top-Secret Memo': '宝藏位置绝密备忘',
 'Triangle Barrier': '三角屏障', 'Trident': '三叉戟', 'Turtle Strap': '海龟挂饰',
 'Tutelary Jewel': '守护宝珠', 'Twilight Horn': '暮光之角',
 'Twinkle Field': '闪烁力场', 'Ultimate Shield': '究极护盾',
 'Under-Eye Mole': '泪痣', 'Under-Rim Glasses': '下框眼镜',
 'Underworld Corpse': '冥界尸骸', 'University Data': '大学资料',
 'Unknown Earthenware': '不明陶器', 'Usa-P Keyholder': '兔P钥匙扣',
 'Vajra': '金刚杵', 'Valkyrie Jewel': '女武神宝珠',
 'Valley Supply Base Floorplan': '溪谷补给基地平面图',
 'Valley Supply Base Guide Map': '溪谷补给基地导览图',
 'Valsaltis': '瓦尔萨尔提斯', 'Venus EG': '维纳斯 EG',
 'Verdant Greenbelt Adventure Guide': '翠绿地带冒险指南',
 'Verdant Greenbelt Gourmet Map': '翠绿地带美食地图',
 'Verdant Greenbelt Guide Map': '翠绿地带导览图',
 'Verdant Greenbelt Treasure Map': '翠绿地带藏宝图',
 'Verse Maiden Boots・ Blue': '歌姬短靴・蓝',
 'Verse Maiden Boots・ Green': '歌姬短靴・绿',
 'Verse Maiden Boots・ Purple': '歌姬短靴・紫',
 'Verse Maiden Boots・ Yellow': '歌姬短靴・黄',
 'Verse Maiden Boots・Pink': '歌姬短靴・粉',
 'Verse Maiden Fan Club Diary': '歌姬粉丝俱乐部日志',
 'Verse Maiden Outfit・ Blue': '歌姬服・蓝',
 'Verse Maiden Outfit・ Green': '歌姬服・绿',
 'Verse Maiden Outfit・ Purple': '歌姬服・紫',
 'Verse Maiden Outfit・ Yellow': '歌姬服・黄',
 'Verse Maiden Outfit・Pink': '歌姬服・粉',
 'Verse Maiden Strap': '歌姬挂饰', 'Victoria Sniper': '维多利亚狙击枪',
 'Vintage Hairstyles': '复古发型集', 'Volume Ribbon': '蓬松缎带',
 'Vomica Nut': '马钱子', 'Warm Feeler': '温暖触须',
 'Watchdog Fur': '看门犬毛', 'Watercolor Set': '水彩颜料套装',
 'Watermarked Monocle': '水纹单片镜', 'Wavy Bob': '波浪波波头',
 'Wavy Pigtails': '波浪双马尾', 'Welfare Divison Daily Report 2': '福利科日报 2',
 'Well-Worn Reference Book': '翻旧的参考书', 'White Crystal': '白水晶',
 'White Egg': '白卵', 'White Gem': '白宝石', 'White Jewel': '白宝珠',
 'White Knee-High Boots': '白色过膝靴',
 'White Ribbon Underwear': '白缎带内衣', 'White Rock': '白岩',
 'White Rubble': '白碎石', 'Wild Fur': '野兽皮毛', 'Wind Slicer': '风之切割者',
 'Wine Velvet': '酒红天鹅绒', 'Wing Cross': '羽翼十字', 'Wing Edge': '羽翼之刃',
 'Wisdom Converter': '智慧转换器', 'Witch Girl Pumpkin Pants': '魔女少女南瓜裤',
 "Witch Girl's Pointed Boots": '魔女少女尖头靴',
 "Witch's Sharp Horn": '魔女利角', 'Withered Leaf': '枯叶',
 'Withered Red Flower': '枯萎的红花', 'Wizard Barricade': '术士壁垒',
 'Wonderful Tortoiseshell Glasses': '精美玳瑁眼镜', 'Wondrous Metal': '奇异金属',
 "Yaksha's Large Fang": '夜叉巨牙', 'Yamate Town Map': '山手町地图',
 'Yellow Fruit': '黄色果实', 'Yellow Scarf': '黄围巾',
 'You In Stripes': '条纹的你', 'You In White': '白衣的你',
 'Éclair Cross': '闪电十字',
}

ITEM.update(ITEM2); ITEM.update(ITEM3)


# ── 数字系列（图纸、通行钥匙、日记……）只写词头，序号原样保留 ──
FAMILY = {
 'Amp Blueprints': '增幅器图纸',
 'Attachment Blueprints': '配件图纸',
 'Protector Blueprints': '护具图纸',
 'Consumable Item Blueprints': '消耗品图纸',
 'Mic Blueprints': '音器图纸',
 'Expansion Disc Vol.': '扩充唱片 Vol.',
 'Pass Key': '通行钥匙',
 'Candid Photo of Miss Kyouka': '响歌小姐抓拍照',
 'Science Journal': '科学期刊',
 "Verse Maiden's Diary": '歌姬的日记',
 "First Generation Manager's Notes": '初代主席笔记',
 "Ruin Investigation Member's Diary": '废墟调查队员日记',
 'Welfare Division Daily Report': '福利科日报',
}


# ── 取词：表内译文 -> 说明文里的既成译法 -> 去掉「+」档位后再试 ──
import re as _re
_PLUS = _re.compile(r'^(.*?)((?:\s*\+)+)\s*$')
_gloss = None


def resolve(en, table):
    """返回中文，取不到返回 None。带 + 的强化档位自动派生。"""
    global _gloss
    if _gloss is None:
        import b4_gloss
        _gloss = {k: v[0] for k, v in b4_gloss.build().items()}
    pool = (table, SKILL, ITEM, _gloss)   # 消耗品在 stItem / stSkill 两张表里同名
    for src in pool:
        if en in src: return src[en]
    k = en.strip()
    for src in pool:
        if k in src: return src[k]
    m = _PLUS.match(en)
    if m:
        root = m.group(1).strip(); n = m.group(2).count('+')
        root = _re.sub(r'\s{2,}', ' ', root)
        for src in pool:
            if root in src: return src[root] + ' +'*n
    root = _re.sub(r'\s{2,}', ' ', k)
    for src in pool:
        if root in src: return src[root]
    m = _re.match(r'^(.*?)\s*(\d+)\s*$', k)      # 数字系列
    if m and m.group(1) in FAMILY:
        return FAMILY[m.group(1)] + ' ' + m.group(2)
    return None


TABLES = {
 'stCharaPlayer': CHARA,
 'stDungeon': DUNGEON,
 'stMapPoint': MAPPOINT,
 'stMaterial': MATERIAL,
 'stCharaMonster': MONSTER,
 'stSkill': SKILL,
 'stItem': ITEM,
}
